[auths]
email = "ethenatx@gmail.com"
token = "eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImV0aGVuYXR4QGdtYWlsLmNvbSIsInN1YiI6IjY4NDg0NWRmOGU5Y2RlOGEwODMyZWVhNSIsImlhdCI6MTc1MDE5OTUwNiwiZXhwIjoxNzUwMjg1OTA2fQ.8Kio-LoLwPS__PKZKMOfv87TheR0Vv3W7JGsV9wENh0"
